import cv2
import numpy as np
img = cv2.imread("input3.jpg",0)
mean = cv2.blur(img,(5,5))
gaussian = cv2.GaussianBlur(img,(9,9),0)
median = cv2.medianBlur(img,15)
cv2.imshow("output.png",img)
cv2.imshow("mean image",mean)
cv2.imshow("gaussian image",gaussian)
cv2.imshow("median image",median)
cv2.imwrite("output_mean.png",mean)
cv2.imwrite("output_gaussian.png",gaussian)
cv2.imwrite("output_median.png",median)
cv2.waitKey(0)
cv2.destroyAllWindows()